name: Deploy to DigitalOcean

on:
    workflow_dispatch:
    # workflow_run:
    # workflows: ["Build"]
    # types:
    #     - completed

jobs:
    deploy:
        runs-on: ubuntu-latest

        # Ensure the deploy job runs only if the build workflow succeeded

        environment: production

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker
              uses: docker/setup-buildx-action@v2

            # Start ssh-agent and add the SSH key with passphrase
            - name: Add SSH key
              run: |
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
                  chmod 600 private_key
                  eval $(ssh-agent -s)
                  echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add private_key
              env:
                  SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}

            - name: Deploy with Docker Compose
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_SERVER }} "cd /path/to/your/app && docker-compose down && docker-compose rm -f && docker-compose up -d"
